plugins {
    id 'com.android.application' version '8.7.2'
    id 'com.google.gms.google-services'
}

static def getDate() { return new Date().format('yyyyMMdd') }

def getVersionName = {
    String semVer = "1.0.0"
    ByteArrayOutputStream TAG = new ByteArrayOutputStream()
    exec {
        try {
            commandLine 'git', 'describe', '--tags'
            ignoreExitValue true
            standardOutput = TAG
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    String tagStr = TAG.toString().trim()
    if (!tagStr.isEmpty()) {
        if (tagStr ==~ /^v?\d+(?:\.\d+)*.*/) {
            return tagStr
        }
    }
    return "v" + semVer
}

def getCFApiKey = {
    String key = System.getenv("CURSEFORGE_API_KEY");
    if(key != null) return key;
    File curseforgeKeyFile = new File("$projectDir/curseforge_key.txt");
    if(curseforgeKeyFile.canRead() && curseforgeKeyFile.isFile()) {
        return curseforgeKeyFile.text;
    }
    logger.warn('BUILD: You have no CurseForge key, the curseforge api will get disabled !');
    return "DUMMY";
}

configurations {
    instrumentedClasspath {
        canBeConsumed = false
        canBeResolved = true
    }
}

android {
    namespace 'net.kdt.pojavlaunch'
    compileSdk = 34

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    signingConfigs {
        customDebug {
            storeFile file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
        release {
            if (project.hasProperty("signingKeystore") && new File(project.property("signingKeystore")).exists()) {
                storeFile file(project.property("signingKeystore"))
                storePassword project.property("signingStorePassword")
                keyAlias project.property("signingKeyAlias")
                keyPassword project.property("signingKeyPassword")
            } else {
                storeFile file("release.keystore")
                storePassword "cslauncher2026"
                keyAlias "cslauncher"
                keyPassword "cslauncher2026"
            }
        }
    }

    defaultConfig {
        applicationId "com.craftstudio.cslauncherv3"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 10000000
        versionName getVersionName()
        multiDexEnabled true
        resValue 'string', 'curseforge_api_key', getCFApiKey()
        externalNativeBuild {
            ndkBuild {
                arguments "APP_SHORT_COMMANDS=true"
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.customDebug
            resValue "string", "app_name", "Blaze Client"
            resValue "string", "app_short_name", "Blaze Client"
            resValue 'string', 'application_package', 'com.craftstudio.cslauncherv3.debug'
            resValue 'string', 'storageProviderAuthorities', 'com.craftstudio.cslauncherv3.scoped.gamefolder.debug'
            resValue 'string', 'shareProviderAuthority', 'com.craftstudio.cslauncherv3.scoped.controlfolder.debug'
        }
        proguard {
            initWith debug
            minifyEnabled true
            shrinkResources true
        }
        proguardNoDebug {
            initWith proguard
            debuggable false
        }
        release {
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            resValue "string", "app_name", "Blaze Client"
            resValue "string", "app_short_name", "Blaze Client"
            resValue 'string', 'storageProviderAuthorities', 'com.craftstudio.cslauncherv3.gamefolder'
            resValue 'string', 'application_package', 'com.craftstudio.cslauncherv3'
        }
        gplay {
            initWith release
            matchingFallbacks = [ 'release' ]
        }
    }

    ndkVersion = "27.3.13750724"

    externalNativeBuild {
        ndkBuild {
            path file('src/main/jni/Android.mk')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    bundle {
        language {
            enableSplit = false
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
        doNotStrip += [
                "**/libcutils.so"
        ]
        pickFirst '**/libbytehook.so'
    }

    buildFeatures {
        prefab true
        buildConfig true
    }

    buildToolsVersion = '34.0.0'
}

afterEvaluate {
    tasks.mergeDebugAssets.dependsOn(":forge_installer:jar", ":arc_dns_injector:jar", ":methods_injector_agent:jar", ":jre_lwjgl3glfw:jar")
    tasks.mergeReleaseAssets.dependsOn(":forge_installer:jar", ":arc_dns_injector:jar", ":methods_injector_agent:jar", ":jre_lwjgl3glfw:jar")
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:32.8.1')
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'commons-codec:commons-codec:1.15'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.viewpager2:viewpager2:1.1.0-beta01'
    implementation 'androidx.annotation:annotation:1.5.0'
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
    implementation 'com.github.duanhong169:checkerboarddrawable:1.0.2'
    implementation 'com.github.PojavLauncherTeam:portrait-sdp:ed33e89cbc'
    implementation 'com.github.PojavLauncherTeam:portrait-ssp:6c02fd739b'
    implementation 'com.github.Mathias-Boulay:ExtendedView:1.0.0'
    implementation 'com.github.Mathias-Boulay:android_gamepad_remapper:2.0.3'
    implementation 'com.github.Mathias-Boulay:virtual-joystick-android:1.14'
    implementation 'org.tukaani:xz:1.8'
    implementation 'net.sourceforge.htmlcleaner:htmlcleaner:2.6.1'
    implementation 'com.bytedance:bytehook:1.0.9'
    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.28'
    implementation 'top.fifthlight.touchcontroller:proxy-client-android:0.0.4'
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation "net.java.dev.jna:jna:5.13.0@aar"
    implementation 'com.google.android.material:material:1.12.0'
}